language: swift
osx_image: xcode9.3
script:
  - xcodebuild clean test -workspace StyledTextKit.xcworkspace -scheme StyledTextKit -destination "platform=iOS Simulator,name=iPhone X,OS=11.3" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet